abstract: GP1022 VFD module controller
author: Kazuhiro Osawa <ko@yappo.ne.jp>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: Device-VFD-GP1022
no_index: 
  directory: 
    - inc
    - t
requires: 
  Device::SerialPort: 0
  Encode: 0
version: 0.01
